project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Juhyeon Park"
  site-url: "jhyeonpark.com"
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/jhyeonpark
format:
  html:
    theme:
        light: [cosmo, theme.scss, anari-custom.scss]
        dark: [cosmo, theme-dark.scss, anari-custom.scss]
    css: styles.css
    
editor: visual

